name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: '34'
        target: 'android-34'
        build-tools: '34.0.0'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew test

    - name: Run integration tests
      run: ./gradlew connectedAndroidTest

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: app/build/outputs/
